services:
  # Unified memory service: single|multi|voyageai modes driven by MODE env var
  memory:
    image: ghcr.io/zanzythebar/mcp-memory-libsql-go:latest
    environment:
      # Core DB
      - LIBSQL_URL=${LIBSQL_URL:-file:/data/libsql.db}
      - LIBSQL_AUTH_TOKEN=${LIBSQL_AUTH_TOKEN}
      # Embeddings
      - EMBEDDING_DIMS=${EMBEDDING_DIMS:-4}
      - EMBEDDINGS_PROVIDER=${EMBEDDINGS_PROVIDER}
      - EMBEDDINGS_ADAPT_MODE=${EMBEDDINGS_ADAPT_MODE}
      # Pooling (optional)
      - DB_MAX_OPEN_CONNS=${DB_MAX_OPEN_CONNS}
      - DB_MAX_IDLE_CONNS=${DB_MAX_IDLE_CONNS}
      - DB_CONN_MAX_IDLE_SEC=${DB_CONN_MAX_IDLE_SEC}
      - DB_CONN_MAX_LIFETIME_SEC=${DB_CONN_MAX_LIFETIME_SEC}
      # Hybrid (optional)
      - HYBRID_SEARCH=${HYBRID_SEARCH}
      - HYBRID_TEXT_WEIGHT=${HYBRID_TEXT_WEIGHT:-0.4}
      - HYBRID_VECTOR_WEIGHT=${HYBRID_VECTOR_WEIGHT:-0.6}
      - HYBRID_RRF_K=${HYBRID_RRF_K:-60}
      # Metrics
      - METRICS_PROMETHEUS=${METRICS_PROMETHEUS:-true}
      - METRICS_PORT=${METRICS_PORT:-9090}
      # Transport / main address (container listens on PORT, host maps via ports below)
      - TRANSPORT=${TRANSPORT:-sse}
      - PORT=${PORT}
      - SSE_ENDPOINT=${SSE_ENDPOINT:-/sse}
      # Multi-project auth toggles
      - MULTI_PROJECT_AUTH_REQUIRED=${MULTI_PROJECT_AUTH_REQUIRED}
      - MULTI_PROJECT_AUTO_INIT_TOKEN=${MULTI_PROJECT_AUTO_INIT_TOKEN}
      - MULTI_PROJECT_DEFAULT_TOKEN=${MULTI_PROJECT_DEFAULT_TOKEN}
      # Runtime mode and misc
      - MODE=${MODE:-single} # single | multi | voyageai
      - PROJECTS_DIR=${PROJECTS_DIR:-/data/projects}
    # Command will be resolved by entrypoint; fall back to default args for compatibility
    command:
      [
        "-transport",
        "${TRANSPORT:-sse}",
        "-addr",
        ":${PORT}",
        "-sse-endpoint",
        "${SSE_ENDPOINT:-/sse}",
      ]
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - type: bind
        source: ./data
        target: /data
        bind:
          create_host_path: true
    healthcheck:
      test: >
        CMD-SHELL
        curl -fsS http://127.0.0.1:${PORT}/healthz || exit 1
      interval: 5s
      timeout: 5s
      start_period: 5s
      retries: 30
