name: Build & Publish Backup Image

on:
  push:
    paths:
      - "docker/backup/**"
      - "scripts/backup_runner.sh"

permissions:
  contents: read
  packages: write

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image name output
        id: image
        run: echo "IMAGE=ghcr.io/${{ github.repository }}-backup" >> $GITHUB_OUTPUT

      - name: Build and push backup image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/backup/Dockerfile
          push: true
          build-args: |
            APP_UID=1000
            APP_GID=1000
          tags: ${{ steps.image.outputs.IMAGE }}:latest
