name: CI - Docker Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  PORT_SSE: 8080
  PORT_METRICS: 9090
  PROFILES: memory
  GO_VERSION: "1.24"
  DOCKER_COMPOSE_VERSION: "v2.39.2"

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Go with caching
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      # Docker Buildx setup (only if multi-arch, else skip QEMU)
      - uses: docker/setup-buildx-action@v2

      # Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Set up Docker Compose
      - uses: docker/compose@main
        with:
          version: ${{ env.DOCKER_COMPOSE_VERSION }}

      # Show versions
      - run: |
          docker --version
          docker compose version

      # Build image
      - run: make docker-build

  test:
    name: Run integration tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - uses: docker/setup-buildx-action@v2
      - uses: docker/compose@v2
        with:
          version: ${{ env.DOCKER_COMPOSE_VERSION }}

      - run: make docker-test
        env:
          PORT_SSE: ${{ env.PORT_SSE }}
          PORT_METRICS: ${{ env.PORT_METRICS }}
          PROFILES: ${{ env.PROFILES }}
