name: CI - Docker Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  docker-test:
    name: Build image and run integration docker-test
    runs-on: ubuntu-latest
    env:
      PORT_SSE: 8080
      PORT_METRICS: 9090
      PROFILES: memory
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose (v2)
        uses: docker/compose-action@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Show Docker and Compose versions
        run: |
          docker --version
          docker compose version

      - name: Run integration docker-test
        run: |
          make docker-build
          make docker-test
        # Allow Docker Compose to use the env vars from the workflow
        env:
          PORT_SSE: ${{ env.PORT_SSE }}
          PORT_METRICS: ${{ env.PORT_METRICS }}
          PROFILES: ${{ env.PROFILES }}

